/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./index.html","./mobileapp.html","./appliances.html","./partners.html","./recipes.html"],
  theme: {
    screens: {
      xs: '420px',
      s: '640px',
      sm: '706px',
      md: '768px',
      lg: '1024px',
      xlg: '1162px',
      '2xlg': '1230px',
      xl: '1280px',
      '2xl': '1536px',
    },

    spacing: {
      px: '1px',
      0: '0px',
      0.5: '0.125em',
      1: '0.25em',
      1.5: '0.375em',
      2: '0.5em',
      2.5: '0.625em',
      3: '0.75em',
      3.5: '0.875em',
      4: '1em',
      5: '1.25em',
      6: '1.5em',
      7: '1.75em',
      8: '2em',
      9: '2.25em',
      10: '2.5em',
      11: '2.75em',
      12: '3em',
      14: '3.5em',
      16: '4em',
      20: '5em',
      24: '6em',
      28: '7em',
      32: '8em',
      36: '9em',
      40: '10em',
      44: '11em',
      48: '12em',
      52: '13em',
      56: '14em',
      60: '15em',
      64: '16em',
      72: '18em',
      80: '20em',
      96: '24em',
    },

    extend: {
      backgroundImage:{
        'cake': 'url("./images/recipe2.jpg")',
        'soup': 'url("./images/recipe.jpg")',
        'peas': 'url("./images/recipe1.png")',
        'rice': 'url("./images/recipe4.jpg")',
        'shrooms': 'url("./images/recipe5.jpg")',
        'cereal': 'url("./images/recipe3.jpg")',
        'rated1': 'url("./images/rated1.jpg")',
        'rated2': 'url("./images/rated2.jpg")',
        'rated3': 'url("./images/rated3.jpg")',
        'rated4': 'url("./images/rated4.jpg")',
        'rated5': 'url("./images/rated5.jpg")',
        'rated6': 'url("./images/rated6.jpg")',
        'rated7': 'url("./images/rated7.jpg")',
        'rated8': 'url("./images/rated8.jpg")',
        'fresh1': 'url("./images/fresh1.jpg")',
        'fresh2': 'url("./images/fresh2.jpg")',
        'fresh3': 'url("./images/fresh3.jpg")',
        'fresh4': 'url("./images/fresh4.jpg")',
        'fresh5': 'url("./images/fresh5.jpg")',
        'fresh6': 'url("./images/fresh6.jpg")',
        'fresh7': 'url("./images/fresh7.jpg")',
        'fresh8': 'url("./images/fresh8.jpg")',
        'pan1': 'url("./images/pan1.jpg")',
        'pan2': 'url("./images/pan2.jpg")',
        'pan3': 'url("./images/pan3.jpg")',
        'pan4': 'url("./images/pan4.jpg")',
        'pan5': 'url("./images/pan5.jpg")',
        'pan6': 'url("./images/pan6.jpg")',
        'pan7': 'url("./images/pan7.jpg")',
        'pan8': 'url("./images/pan8.jpg")',
        'fryer1': 'url("./images/fryer1.jpg")',
        'fryer2': 'url("./images/fryer2.jpg")',
        'fryer3': 'url("./images/fryer3.jpg")',
        'fryer4': 'url("./images/fryer4.jpg")',
        'fryer5': 'url("./images/fryer5.jpg")',
        'fryer6': 'url("./images/fryer6.jpg")',
        'fryer7': 'url("./images/fryer7.jpg")',
        'fryer8': 'url("./images/fryer8.jpg")',
        'instant1': 'url("./images/instant1.jpg")',
        'instant2': 'url("./images/instant2.jpg")',
        'instant3': 'url("./images/instant3.jpg")',
        'instant4': 'url("./images/instant4.jpg")',
        'instant5': 'url("./images/instant5.jpg")',
        'instant6': 'url("./images/instant6.jpg")',
        'instant7': 'url("./images/instant7.jpg")',
        'instant8': 'url("./images/instant8.jpg")',
        'mix1': 'url("./images/mix1.jpg")',
        'mix2': 'url("./images/mix2.jpg")',
        'mix3': 'url("./images/mix3.jpg")',
        'mix4': 'url("./images/mix4.jpg")',
        'mix5': 'url("./images/mix5.jpg")',
        'mix6': 'url("./images/mix6.jpg")',
        'mix7': 'url("./images/mix7.jpg")',
        'mix8': 'url("./images/mix8.jpg")',
      },

      fontFamily: {
        dmsans: "DM Sans",
        walsheim: "GT Walsheim",
        founders : "Founders"
      },

      colors: {
        coal : "rgb(31,29,26)",
        metal : "rgb(143,143,143)",
        squash : "rgb(254,210,67)",
        "squash-tint" : "rgb(255,237,180)",
        "squash-shade" : "rgb(80,74,36)",
        carrot : "rgb(255,127,17)",
        "carrot-shade" : "rgb(89,45,5)",
        "carrot-tint" : "rgb(253,201,156)",
        rocket : "rgb(68,175,105)",
        "rocket-tint" : "rgb(186,227,200)",
        "rocket-shade" : "rgb(38,56,43)",
        tomato : "rgb(255,69,69)",
        "tomato-shade" : "rgb(71,16,16)",
        "tomato-tint" : "rgb(249,201,200)",
        crema : "rgb(252,240,213)",
        "crema-tint" : "rgb(254,249,238)",
        aubergine : "rgb(117,8,58)",
        "aubergine-shade" : "rgb(63,16,38)",
        "aubergine-tint" : "rgb(246,183,209)",
      },
     fontSize: {
        '10xl': ['8.75em', { lineHeight: '1' }],
      },

      borderRadius: {
        '4xl': "2rem",
        '5xl': "2.5rem",
        '6xl': "3rem",
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
